import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'


const NetflixSans = localFont({
  src: './NetflixSans-Regular.woff2',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${NetflixSans.className}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
